version:  '3.8'

services:

  couchbase:
    image: "couchbase:latest"
    networks:
      - nosql
    ports:
      - 8091:8091
      - 8094:8094

  mongodb:
    image: "mongo:latest"
    networks:
      - nosql
    ports:
      - 27017:27017

networks:
  nosql: