version:  '3.8'

services:

  couchbase:
    image: "couchbase:latest"
    networks:
      - nosql
    ports:
      - 8091-8097:8091-8097
      - 9123:9123
      - 11207:11207
      - 11210:11210
      - 11280:11280
      - 18091-18097:18091-18097

  mongodb:
    image: "mongo:latest"
    networks:
      - nosql
    ports:
      - 27017:27017

networks:
  nosql: